GET http://localhost:8080/user/65723d4801b2ee407d502d00
Accept: application/json

###

GET http://localhost:8080/user/list
Accept: application/json

###

POST http://localhost:8080/user/create
Content-Type: application/json

{
  "login": "qqq",
  "enabled": true,
  "password": "password"
}
###

PUT http://localhost:8080/user/update
Content-Type: application/json

{
  "id": "65723d4801b2ee407d502d00",
  "version": 1,
  "name": "ASdasfdsfgdfgdfg",
  "enabled": false
}

###