logger:
  level: "debug"
  development: true

server:
  port: 8080

mongo:
  host: "mongo"
  port: 27017
  database: "auth"
  replica-set: rs0

kafka:
  brokers: "redpanda:29092"
  schema-registry:
    url: "http://redpanda:8081"
    auto-register-schemas: true
  consumers-config:
    default-group-id: "ecommerce-auth-service"
    default-auto-offset-reset: "earliest"
    consumers:
      - name: "tenant-events"
        topic: "tenant.tenant.events"
        max-retries: 5
        initial-backoff: 2s
        max-backoff: 30s
        enable-dlq: true

observability:
  otel-collector-endpoint: "otel-collector-opentelemetry-collector.observability.svc:4317"
  tracing:
    enabled: true
  metrics:
    enabled: false

pprof:
  enabled: true
  port: 6060

clients:
  tenant-service:
    base-url: "http://ecommerce-tenant-service:8080"

security:
  token:
    public-key: "eb6ebefd6a2b0a304d43c2ccca329aef0a1439d429dbe8ca9b6190622ce38341"
    service-token: "v4.public.eyJleHAiOiIyMDM2LTA0LTA3VDE1OjM5OjU4KzAyOjAwIiwiaWF0IjoiMjAyNi0wNC0xMFQxNTozOTo1OCswMjowMCIsIm5iZiI6IjIwMjYtMDQtMTBUMTU6Mzk6NTgrMDI6MDAiLCJwZXJtaXNzaW9ucyI6WyJ0ZW5hbnRzOnJlYWQiXSwicm9sZSI6InNlcnZpY2VfYWNjb3VudCIsInNlcnZpY2VfbmFtZSI6ImF1dGgtc2VydmljZSIsInN1YiI6InNlcnZpY2U6YXV0aC1zZXJ2aWNlIiwidHlwZSI6ImFjY2VzcyJ9C16v0j6EEkb1oIKscU0IBUf8D13aGG2lHA6x5JfLipx4smFhz_2wc-B9XSV8q-jVMECxwk_XUew9QTKF31HYCQ"

token:
  private-key: "e9bc26b8119fa3ccd616e3bd05603507fd308cb30a0a99c4b858c621dd147f1beb6ebefd6a2b0a304d43c2ccca329aef0a1439d429dbe8ca9b6190622ce38341"
  access-token-duration: 15m
  refresh-token-duration: 48h

rate-limit:
  login-tokens: 5        # Number of login attempts allowed
  login-interval: 1m     # Time window for login attempts

# Initial super admin user (created on first startup if not exists)
admin:
  initial-user:
    enabled: true
    email: "admin@localhost.com"
    password: "pass"
    first-name: "Super"
    last-name: "Admin"

permissions:
  roles:
    - name: "super_admin"
      description: "Full access to all resources"
      permissions:
        - "users:read"
        - "users:write"
        - "users:delete"
        - "products:read"
        - "products:write"
        - "products:delete"
        - "categories:read"
        - "categories:write"
        - "categories:delete"
        - "attributes:read"
        - "attributes:write"
        - "attributes:delete"

    - name: "catalog_manager"
      description: "Can manage products, categories and attributes"
      permissions:
        - "products:read"
        - "products:write"
        - "products:delete"
        - "categories:read"
        - "categories:write"
        - "categories:delete"
        - "attributes:read"
        - "attributes:write"
        - "attributes:delete"

    - name: "viewer"
      description: "Read-only access"
      permissions:
        - "users:read"
        - "products:read"
        - "categories:read"
        - "attributes:read"
